// Code generated by protoc-gen-go.
// source: pb_defs/chord.proto
// DO NOT EDIT!

/*
Package dendrite is a generated protocol buffer package.

It is generated from these files:
	pb_defs/chord.proto

It has these top-level messages:
	MsgPing
	MsgAck
	MsgJoinRequest
	MsgNodeJoined
	MsgFindSuccessorRequest
	MsgFindSuccessorReply
	MsgSPRequest
	MsgSPReply
*/
package dendrite

import proto "code.google.com/p/goprotobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type MsgPing struct {
	Version          *int64 `protobuf:"varint,1,req,name=version" json:"version,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgPing) Reset()         { *m = MsgPing{} }
func (m *MsgPing) String() string { return proto.CompactTextString(m) }
func (*MsgPing) ProtoMessage()    {}

func (m *MsgPing) GetVersion() int64 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

type MsgAck struct {
	Val              *bool  `protobuf:"varint,1,req,name=val" json:"val,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgAck) Reset()         { *m = MsgAck{} }
func (m *MsgAck) String() string { return proto.CompactTextString(m) }
func (*MsgAck) ProtoMessage()    {}

func (m *MsgAck) GetVal() bool {
	if m != nil && m.Val != nil {
		return *m.Val
	}
	return false
}

type MsgJoinRequest struct {
	ClusterName      *string `protobuf:"bytes,1,req,name=clusterName" json:"clusterName,omitempty"`
	Uuid             *string `protobuf:"bytes,2,req,name=uuid" json:"uuid,omitempty"`
	Addr             *string `protobuf:"bytes,3,req,name=addr" json:"addr,omitempty"`
	Location         *string `protobuf:"bytes,4,req,name=location" json:"location,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgJoinRequest) Reset()         { *m = MsgJoinRequest{} }
func (m *MsgJoinRequest) String() string { return proto.CompactTextString(m) }
func (*MsgJoinRequest) ProtoMessage()    {}

func (m *MsgJoinRequest) GetClusterName() string {
	if m != nil && m.ClusterName != nil {
		return *m.ClusterName
	}
	return ""
}

func (m *MsgJoinRequest) GetUuid() string {
	if m != nil && m.Uuid != nil {
		return *m.Uuid
	}
	return ""
}

func (m *MsgJoinRequest) GetAddr() string {
	if m != nil && m.Addr != nil {
		return *m.Addr
	}
	return ""
}

func (m *MsgJoinRequest) GetLocation() string {
	if m != nil && m.Location != nil {
		return *m.Location
	}
	return ""
}

type MsgNodeJoined struct {
	ClusterName      *string `protobuf:"bytes,1,req,name=clusterName" json:"clusterName,omitempty"`
	Version          *int64  `protobuf:"varint,2,req,name=version" json:"version,omitempty"`
	Uuid             *string `protobuf:"bytes,3,req,name=uuid" json:"uuid,omitempty"`
	Addr             *string `protobuf:"bytes,4,req,name=addr" json:"addr,omitempty"`
	Location         *string `protobuf:"bytes,5,req,name=location" json:"location,omitempty"`
	PredcessorKey    []byte  `protobuf:"bytes,6,req,name=predcessor_key" json:"predcessor_key,omitempty"`
	PredcessorUuid   *string `protobuf:"bytes,7,req,name=predcessor_uuid" json:"predcessor_uuid,omitempty"`
	PredcessorAddr   *string `protobuf:"bytes,8,req,name=predcessor_addr" json:"predcessor_addr,omitempty"`
	SuccessorKey     []byte  `protobuf:"bytes,9,req,name=successor_key" json:"successor_key,omitempty"`
	SuccessorUuid    *string `protobuf:"bytes,10,req,name=successor_uuid" json:"successor_uuid,omitempty"`
	SuccessorAddr    *string `protobuf:"bytes,11,req,name=successor_addr" json:"successor_addr,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgNodeJoined) Reset()         { *m = MsgNodeJoined{} }
func (m *MsgNodeJoined) String() string { return proto.CompactTextString(m) }
func (*MsgNodeJoined) ProtoMessage()    {}

func (m *MsgNodeJoined) GetClusterName() string {
	if m != nil && m.ClusterName != nil {
		return *m.ClusterName
	}
	return ""
}

func (m *MsgNodeJoined) GetVersion() int64 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *MsgNodeJoined) GetUuid() string {
	if m != nil && m.Uuid != nil {
		return *m.Uuid
	}
	return ""
}

func (m *MsgNodeJoined) GetAddr() string {
	if m != nil && m.Addr != nil {
		return *m.Addr
	}
	return ""
}

func (m *MsgNodeJoined) GetLocation() string {
	if m != nil && m.Location != nil {
		return *m.Location
	}
	return ""
}

func (m *MsgNodeJoined) GetPredcessorKey() []byte {
	if m != nil {
		return m.PredcessorKey
	}
	return nil
}

func (m *MsgNodeJoined) GetPredcessorUuid() string {
	if m != nil && m.PredcessorUuid != nil {
		return *m.PredcessorUuid
	}
	return ""
}

func (m *MsgNodeJoined) GetPredcessorAddr() string {
	if m != nil && m.PredcessorAddr != nil {
		return *m.PredcessorAddr
	}
	return ""
}

func (m *MsgNodeJoined) GetSuccessorKey() []byte {
	if m != nil {
		return m.SuccessorKey
	}
	return nil
}

func (m *MsgNodeJoined) GetSuccessorUuid() string {
	if m != nil && m.SuccessorUuid != nil {
		return *m.SuccessorUuid
	}
	return ""
}

func (m *MsgNodeJoined) GetSuccessorAddr() string {
	if m != nil && m.SuccessorAddr != nil {
		return *m.SuccessorAddr
	}
	return ""
}

type MsgFindSuccessorRequest struct {
	ClusterName      *string `protobuf:"bytes,1,req,name=clusterName" json:"clusterName,omitempty"`
	Version          *int64  `protobuf:"varint,2,req,name=version" json:"version,omitempty"`
	Key              []byte  `protobuf:"bytes,3,req,name=key" json:"key,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgFindSuccessorRequest) Reset()         { *m = MsgFindSuccessorRequest{} }
func (m *MsgFindSuccessorRequest) String() string { return proto.CompactTextString(m) }
func (*MsgFindSuccessorRequest) ProtoMessage()    {}

func (m *MsgFindSuccessorRequest) GetClusterName() string {
	if m != nil && m.ClusterName != nil {
		return *m.ClusterName
	}
	return ""
}

func (m *MsgFindSuccessorRequest) GetVersion() int64 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *MsgFindSuccessorRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type MsgFindSuccessorReply struct {
	ClusterName      *string `protobuf:"bytes,1,req,name=clusterName" json:"clusterName,omitempty"`
	Version          *int64  `protobuf:"varint,2,req,name=version" json:"version,omitempty"`
	SuccessorKey     []byte  `protobuf:"bytes,3,req,name=successor_key" json:"successor_key,omitempty"`
	SuccessorUuid    *string `protobuf:"bytes,4,req,name=successor_uuid" json:"successor_uuid,omitempty"`
	SuccessorAddr    *string `protobuf:"bytes,5,req,name=successor_addr" json:"successor_addr,omitempty"`
	Authoritative    *bool   `protobuf:"varint,6,req,name=authoritative" json:"authoritative,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgFindSuccessorReply) Reset()         { *m = MsgFindSuccessorReply{} }
func (m *MsgFindSuccessorReply) String() string { return proto.CompactTextString(m) }
func (*MsgFindSuccessorReply) ProtoMessage()    {}

func (m *MsgFindSuccessorReply) GetClusterName() string {
	if m != nil && m.ClusterName != nil {
		return *m.ClusterName
	}
	return ""
}

func (m *MsgFindSuccessorReply) GetVersion() int64 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *MsgFindSuccessorReply) GetSuccessorKey() []byte {
	if m != nil {
		return m.SuccessorKey
	}
	return nil
}

func (m *MsgFindSuccessorReply) GetSuccessorUuid() string {
	if m != nil && m.SuccessorUuid != nil {
		return *m.SuccessorUuid
	}
	return ""
}

func (m *MsgFindSuccessorReply) GetSuccessorAddr() string {
	if m != nil && m.SuccessorAddr != nil {
		return *m.SuccessorAddr
	}
	return ""
}

func (m *MsgFindSuccessorReply) GetAuthoritative() bool {
	if m != nil && m.Authoritative != nil {
		return *m.Authoritative
	}
	return false
}

type MsgSPRequest struct {
	ClusterName      *string `protobuf:"bytes,1,req,name=clusterName" json:"clusterName,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgSPRequest) Reset()         { *m = MsgSPRequest{} }
func (m *MsgSPRequest) String() string { return proto.CompactTextString(m) }
func (*MsgSPRequest) ProtoMessage()    {}

func (m *MsgSPRequest) GetClusterName() string {
	if m != nil && m.ClusterName != nil {
		return *m.ClusterName
	}
	return ""
}

type MsgSPReply struct {
	ClusterName      *string `protobuf:"bytes,1,req,name=clusterName" json:"clusterName,omitempty"`
	SuccessorKey     []byte  `protobuf:"bytes,2,req,name=successor_key" json:"successor_key,omitempty"`
	SuccessorUuid    *string `protobuf:"bytes,3,req,name=successor_uuid" json:"successor_uuid,omitempty"`
	SuccessorAddr    *string `protobuf:"bytes,4,req,name=successor_addr" json:"successor_addr,omitempty"`
	PredcessorKey    []byte  `protobuf:"bytes,5,req,name=predcessor_key" json:"predcessor_key,omitempty"`
	PredcessorUuid   *string `protobuf:"bytes,6,req,name=predcessor_uuid" json:"predcessor_uuid,omitempty"`
	PredcessorAddr   *string `protobuf:"bytes,7,req,name=predcessor_addr" json:"predcessor_addr,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgSPReply) Reset()         { *m = MsgSPReply{} }
func (m *MsgSPReply) String() string { return proto.CompactTextString(m) }
func (*MsgSPReply) ProtoMessage()    {}

func (m *MsgSPReply) GetClusterName() string {
	if m != nil && m.ClusterName != nil {
		return *m.ClusterName
	}
	return ""
}

func (m *MsgSPReply) GetSuccessorKey() []byte {
	if m != nil {
		return m.SuccessorKey
	}
	return nil
}

func (m *MsgSPReply) GetSuccessorUuid() string {
	if m != nil && m.SuccessorUuid != nil {
		return *m.SuccessorUuid
	}
	return ""
}

func (m *MsgSPReply) GetSuccessorAddr() string {
	if m != nil && m.SuccessorAddr != nil {
		return *m.SuccessorAddr
	}
	return ""
}

func (m *MsgSPReply) GetPredcessorKey() []byte {
	if m != nil {
		return m.PredcessorKey
	}
	return nil
}

func (m *MsgSPReply) GetPredcessorUuid() string {
	if m != nil && m.PredcessorUuid != nil {
		return *m.PredcessorUuid
	}
	return ""
}

func (m *MsgSPReply) GetPredcessorAddr() string {
	if m != nil && m.PredcessorAddr != nil {
		return *m.PredcessorAddr
	}
	return ""
}

func init() {
}
